---
language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update && sudo apt-get install -y libsdl2-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sdl2; fi
script:
  - make
